services:
  postgres:
    image: postgres:16-alpine
    container_name: revista-sigilosa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonido_sigiloso
    ports:
      - "5432:5432"
    volumes:
      - /Users/jomsox/Library/CloudStorage/Dropbox/nodosigiloso/RevistaSigilosaDB:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
